<a href="https://colab.research.google.com/github/sxm18940/ML_Assignment5/blob/main/ML_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# import the libraries 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn import preprocessing, metrics
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
sns.set(style="white", color_codes=True)
import warnings
warnings.filterwarnings("ignore")

In [5]:
#Question-1: Principal Component Analysis
from google.colab import drive
drive.mount('/content/gdrive')
dataframe = pd.read_csv("gdrive/My Drive/C/CC.csv")
dataframe.head()

Mounted at /content/gdrive


CUST_ID      BALANCE  BALANCE_FREQUENCY  PURCHASES  ONEOFF_PURCHASES  \
0  C10001    40.900749           0.818182      95.40              0.00   
1  C10002  3202.467416           0.909091       0.00              0.00   
2  C10003  2495.148862           1.000000     773.17            773.17   
3  C10004  1666.670542           0.636364    1499.00           1499.00   
4  C10005   817.714335           1.000000      16.00             16.00   

   INSTALLMENTS_PURCHASES  CASH_ADVANCE  PURCHASES_FREQUENCY  \
0                    95.4      0.000000             0.166667   
1                     0.0   6442.945483             0.000000   
2                     0.0      0.000000             1.000000   
3                     0.0    205.788017             0.083333   
4                     0.0      0.000000             0.083333   

   ONEOFF_PURCHASES_FREQUENCY  PURCHASES_INSTALLMENTS_FREQUENCY  \
0                    0.000000                          0.083333   
1                    0.000000                          0.000000   
2                    1.000000                          0.000000   
3                    0.083333                          0.000000   
4                    0.083333                          0.000000   

   CASH_ADVANCE_FREQUENCY  CASH_ADVANCE_TRX  PURCHASES_TRX  CREDIT_LIMIT  \
0                0.000000                 0              2        1000.0   
1                0.250000                 4              0        7000.0   
2                0.000000                 0             12        7500.0   
3                0.083333                 1              1        7500.0   
4                0.000000                 0              1        1200.0   

      PAYMENTS  MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  TENURE  
0   201.802084        139.509787          0.000000      12  
1  4103.032597       1072.340217          0.222222      12  
2   622.066742        627.284787          0.000000      12  
3     0.000000               NaN          0.000000      12  
4   678.334763        244.791237          0.000000      12

In [6]:
dataframe.isnull().any()

CUST_ID                             False
BALANCE                             False
BALANCE_FREQUENCY                   False
PURCHASES                           False
ONEOFF_PURCHASES                    False
INSTALLMENTS_PURCHASES              False
CASH_ADVANCE                        False
PURCHASES_FREQUENCY                 False
ONEOFF_PURCHASES_FREQUENCY          False
PURCHASES_INSTALLMENTS_FREQUENCY    False
CASH_ADVANCE_FREQUENCY              False
CASH_ADVANCE_TRX                    False
PURCHASES_TRX                       False
CREDIT_LIMIT                         True
PAYMENTS                            False
MINIMUM_PAYMENTS                     True
PRC_FULL_PAYMENT                    False
TENURE                              False
dtype: bool

In [7]:
dataframe.fillna(dataframe.mean(), inplace=True)
dataframe.isnull().any()

CUST_ID                             False
BALANCE                             False
BALANCE_FREQUENCY                   False
PURCHASES                           False
ONEOFF_PURCHASES                    False
INSTALLMENTS_PURCHASES              False
CASH_ADVANCE                        False
PURCHASES_FREQUENCY                 False
ONEOFF_PURCHASES_FREQUENCY          False
PURCHASES_INSTALLMENTS_FREQUENCY    False
CASH_ADVANCE_FREQUENCY              False
CASH_ADVANCE_TRX                    False
PURCHASES_TRX                       False
CREDIT_LIMIT                        False
PAYMENTS                            False
MINIMUM_PAYMENTS                    False
PRC_FULL_PAYMENT                    False
TENURE                              False
dtype: bool

In [8]:
x = dataframe.iloc[:,1:-1]
y = dataframe.iloc[:,-1]
print(x.shape,y.shape)

(8950, 16) (8950,)


In [9]:
# a. Apply PCA on CC dataset.
#Datasets can be analyzed with PCA so that redundant features can be removed without losing too much information.
pca = PCA(3)
x_pca = pca.fit_transform(x)
principalDataframe = pd.DataFrame(data = x_pca, columns = ['principal_component1', 'principal_component2', 'principal_component3'])
finalDataframe = pd.concat([principalDataframe, dataframe.iloc[:,-1]], axis = 1)
finalDataframe.head()

principal_component1  principal_component2  principal_component3  TENURE
0          -4326.383979            921.566882            183.708383      12
1           4118.916665          -2432.846346           2369.969289      12
2           1497.907641          -1997.578694          -2125.631328      12
3           1394.548536          -1488.743453          -2431.799649      12
4          -3743.351896            757.342657            512.476492      12

In [10]:
# b. Apply k-means algorithm on the PCA result and report your observation if the silhouette score has improved or not?

X = finalDataframe.iloc[:,0:-1]
y = finalDataframe.iloc[:,-1]

In [15]:
nclusters = 3 
kmeans = KMeans(n_clusters=nclusters)
kmeans.fit(X)
y_cluster_kmeans = kmeans.predict(X)
# predictions by the classifier
print(classification_report(y, y_cluster_kmeans, zero_division=1))
print(confusion_matrix(y, y_cluster_kmeans))
#Accuracyt Evaluation
train_accuracy = accuracy_score(y, y_cluster_kmeans)
print("\n Accuracy for our Training dataset with PCA is ", train_accuracy)
#sihouette Score Calculation
score = metrics.silhouette_score(X, y_cluster_kmeans)
print("Silhouette Score is ",score) 

              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00     204.0
           7       1.00      0.00      0.00     190.0
           8       1.00      0.00      0.00     196.0
           9       1.00      0.00      0.00     175.0
          10       1.00      0.00      0.00     236.0
          11       1.00      0.00      0.00     365.0
          12       1.00      0.00      0.00    7584.0

    accuracy                           0.00    8950.0
   macro avg       0.70      0.30      0.00    8950.0
weighted avg       1.00      0.00      0.00    8950.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [  28  175    1    0    0    0    0    0    0    0]
 [  15  173    2    0    0   

In [35]:
# c. Perform Scaling+PCA+K-Means and report performance.

x = dataframe.iloc[:,1:-1]
y = dataframe.iloc[:,-1]
print(x.shape,y.shape)

(8950, 16) (8950,)


In [16]:
## Scaling the dataset
scaler = StandardScaler()
scaler.fit(x)
X_scaled_array = scaler.transform(x)
pca = PCA(3)
# Determine transformed features
x_pca = pca.fit_transform(X_scaled_array)
principalDataframe = pd.DataFrame(data = x_pca, columns = ['principal_component1', 'principal_component2','principal_component3'])
finalDataframe = pd.concat([principalDataframe, dataframe.iloc[:,-1]], axis = 1)
finalDataframe.head()

principal_component1  principal_component2  principal_component3  TENURE
0             -1.718893             -1.072941              0.535689      12
1             -1.169306              2.509312              0.627887      12
2              0.938414             -0.382594              0.161289      12
3             -0.907502              0.045855              1.521644      12
4             -1.637830             -0.684974              0.425710      12

In [17]:
x = finalDataframe.iloc[:,0:-1]
y = finalDataframe["TENURE"]
print(X.shape,y.shape)

(8950, 3) (8950,)


In [20]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.34,random_state=0)
nclusters = 3 
kmeans = KMeans(n_clusters=nclusters)
kmeans.fit(X_train,y_train)
y_clus_train = kmeans.predict(X_train)

#predictions by the classifier
print(classification_report(y_train, y_clus_train, zero_division=1))
print(confusion_matrix(y_train, y_clus_train))

train_accuracy = accuracy_score(y_train, y_clus_train)
print("Accuracy for our Training dataset with PCA is", train_accuracy)
#Calculation of sihouette Score
score = metrics.silhouette_score(X_train, y_clus_train)
print("Silhouette Score is ",score)

              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00     139.0
           7       1.00      0.00      0.00     135.0
           8       1.00      0.00      0.00     128.0
           9       1.00      0.00      0.00     118.0
          10       1.00      0.00      0.00     151.0
          11       1.00      0.00      0.00     262.0
          12       1.00      0.00      0.00    4974.0

    accuracy                           0.00    5907.0
   macro avg       0.70      0.30      0.00    5907.0
weighted avg       1.00      0.00      0.00    5907.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [ 105    4   30    0    0    0    0    0    0    0]
 [ 108    1   26    0    0   

In [15]:
# predict the cluster for each testing data point
y_clus_test = km.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_clus_test, zero_division=1))
print(confusion_matrix(y_test, y_clus_test))

train_accuracy = accuracy_score(y_test, y_clus_test)
print("\nAccuracy for our Training dataset with PCA:", train_accuracy)

#Calculating sihouette Score
score = metrics.silhouette_score(X_test, y_clus_test)
print("Sihouette Score: ",score)   #ranges from -1 to +1, high value shows that it is matched more


              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00      65.0
           7       1.00      0.00      0.00      55.0
           8       1.00      0.00      0.00      68.0
           9       1.00      0.00      0.00      57.0
          10       1.00      0.00      0.00      85.0
          11       1.00      0.00      0.00     103.0
          12       1.00      0.00      0.00    2610.0

    accuracy                           0.00    3043.0
   macro avg       0.70      0.30      0.00    3043.0
weighted avg       1.00      0.00      0.00    3043.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   3   41   21    0    0    0    0    0    0    0]
 [   0   43   12    0    0   

In [22]:
#Question-2: Use pd_speech_features.csv

dataframe_pd = pd.read_csv("gdrive/My Drive/P/pd_speech_features.csv")
dataframe_pd.head()

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
0   0       1  0.85247  0.71826  0.57227        240               239   
1   0       1  0.76686  0.69481  0.53966        234               233   
2   0       1  0.85083  0.67604  0.58982        232               231   
3   1       0  0.41121  0.79672  0.59257        178               177   
4   1       0  0.32790  0.79782  0.53028        236               235   

   meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
0          0.008064            0.000087       0.00218  ...   
1          0.008258            0.000073       0.00195  ...   
2          0.008340            0.000060       0.00176  ...   
3          0.010858            0.000183       0.00419  ...   
4          0.008162            0.002669       0.00535  ...   

   tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                     1.5620                     2.6445   
1                     1.5589                     3.6107   
2                     1.5643                     2.3308   
3                     3.7805                     3.5664   
4                     6.1727                     5.8416   

   tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                     3.8686                     4.2105   
1                    23.5155                    14.1962   
2                     9.4959                    10.7458   
3                     5.2558                    14.0403   
4                     6.0805                     5.7621   

   tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                     5.1221                     4.4625   
1                    11.0261                     9.5082   
2                    11.0177                     4.8066   
3                     4.2235                     4.6857   
4                     7.7817                    11.6891   

   tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                     2.6202                     3.0004   
1                     6.5245                     6.3431   
2                     2.9199                     3.1495   
3                     4.8460                     6.2650   
4                     8.2103                     5.0559   

   tqwt_kurtosisValue_dec_36  class  
0                    18.9405      1  
1                    45.1780      1  
2                     4.7666      1  
3                     4.0603      1  
4                     6.1164      1  

[5 rows x 755 columns]

In [23]:
dataframe_pd.isnull().any()

id                           False
gender                       False
PPE                          False
DFA                          False
RPDE                         False
                             ...  
tqwt_kurtosisValue_dec_33    False
tqwt_kurtosisValue_dec_34    False
tqwt_kurtosisValue_dec_35    False
tqwt_kurtosisValue_dec_36    False
class                        False
Length: 755, dtype: bool

In [24]:
X = dataframe_pd.drop('class',axis=1).values
Y = dataframe_pd['class'].values

In [25]:
# a. Perform Scaling
#Scaling Data
scaler = StandardScaler()
X_Scale = scaler.fit_transform(X)

In [33]:
# b. Apply PCA (k=3)
# Apply PCA with k =3
pca3 = PCA(n_components=3)
principalComponents = pca3.fit_transform(X_Scale)
principalDataframe = pd.DataFrame(data = principalComponents, columns = ['principal_component1', 'principal_component2','Principal_Component3'])
finalDataframe = pd.concat([principalDataframe, dataframe_pd[['class']]], axis = 1)
finalDataframe.head()

principal_component1  principal_component2  Principal_Component3  class
0            -10.047372              1.471072             -6.846405      1
1            -10.637725              1.583744             -6.830978      1
2            -13.516185             -1.253545             -6.818699      1
3             -9.155085              8.833578             15.290899      1
4             -6.764471              4.611446             15.637118      1

In [29]:
X = finalDataframe.drop('class',axis=1).values
Y = finalDataframe['class'].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,random_state=0)

In [34]:
# c. Use SVM to report performance
from sklearn.svm import SVC
SVMClassifier = SVC()
SVMClassifier.fit(X_train, Y_train)
y_pred = SVMClassifier.predict(X_test)
# predictions by the classifier
print(classification_report(Y_test, y_pred, zero_division=1))
print(confusion_matrix(Y_test, y_pred))
# Accuracy score
glass_acc_svc = accuracy_score(y_pred,Y_test)
print('Accuracy is',glass_acc_svc)
#silhouette Score Calculation
score = metrics.silhouette_score(X_test, y_pred)
print("Silhouette Score is: ",score) 

              precision    recall  f1-score   support

           0       0.67      0.42      0.52        57
           1       0.83      0.93      0.88       170

    accuracy                           0.80       227
   macro avg       0.75      0.68      0.70       227
weighted avg       0.79      0.80      0.79       227

[[ 24  33]
 [ 12 158]]
Accuracy is 0.801762114537445
Silhouette Score is:  0.2543208585711132


In [37]:
#Question-3: Apply Linear Discriminant Analysis (LDA) on Iris.csv dataset to reduce dimensionality of data to k=2. 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
df_iris = pd.read_csv("gdrive/My Drive/Iris/Iris.csv")

In [38]:
df_iris.isnull().any()

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [39]:
x = df_iris.iloc[:,1:-1]
y = df_iris.iloc[:,-1]
print(x.shape,y.shape)

(150, 4) (150,)


In [40]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)


In [41]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
LE = LabelEncoder()
y = LE.fit_transform(y)

In [42]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)
print(X_train.shape,X_test.shape)

(105, 2) (45, 2)


#Question-4: Briefly identify the difference between PCA and LDA 
Principal Component Analysis (PCA) and Linear Discriminant Analysis (LDA) are two of the most popular dimensionality reduction techniques. 
Both methods are used to reduce the number of features in the dataset while retaining as much information as possible.
PCA: Principal Component Analysis (PCA) works by identifying the direction (component) that maximizes the variance of a data set. 
That is, it tries to find a linear combination of features that captures as much variance as possible. 
The first component captures the maximum variance, the second component is orthogonal to the first and captures the remaining variance. 
PCA is a useful technique for dimensionality reduction when there is a linear relationship between features in the data
LDA: Linear Discriminant Analysis (LDA) is another linear transformation technique used for dimensionality reduction. 
However, unlike PCA, LDA is a method of supervised learning. That is, class labels are taken into account when finding the direction of maximum variance. 
This makes LDA particularly suitable for classification tasks where we want to maximize class separability.
PCA is an unsupervised learning algorithm and LDA is a supervised learning algorithm. 
This means that PCA finds the direction of maximum variance, independent of class labels, and LDA finds the direction of maximum class separability.
In general, for classification purposes, LDA should be used.
If your goal is just to find patterns in the data (not classify) then PCA might work better.
If noise dominates the data set, LDA may give better results even if the goal is not classification. 
Because LDA makes stronger assumptions about the structure of the data, it often performs better than PCA when the dataset fits those assumptions, but performs worse when it doesn't.